### ISSUE TITLE
Run AMBER on random subset of reads

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#16]

**Comment by verku** [comment]
1 million reads, @bilalbioinfo will confirm with Tom

In samtools, a proportion of reads can be extracted (randomly) with `samtools view -s`. Seed can be provided as well. See GenErode pipeline for example code.

**Comment by bilalbioinfo** [comment]
Yes, randomly sub-sampling to 1 million reads would be enough for our purpose!
in case someone want to see fine-scalled patterns, then 10 million would be a number of target, but for our case, 1 million would be good enough

**Comment by verku** [comment]
OK! We could provide this as an option in the `modules.config` file then for now (i.e. the config file for more advanced pipeline users)

**Comment by verku** [comment]
In the current version, any read can be subsampled. We can discuss if/how to restrict the subsampling.
