### ISSUE TITLE
Add preseq module and subworkflow

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#28]

**Comment by verku** [comment]
Add to processed_fastq_raw_bam_qc subworkflow for now

**Comment by bilalbioinfo** [comment]
working on it!

**Comment by bilalbioinfo** [comment]
preseq module added 7204c2e883c7d00cb6f9a32675b120b17042f529
working on adding the module to plot the results

**Comment by bilalbioinfo** [comment]
now running preseq and plotting as well 38a6d4aa762ddada31da11224f9b8d2ce285f99d

**Comment by verku** [comment]
- Run a test on a large dataset, if it is very slow, consider subsampling
- Turn preseq module on/off with if clause and as parameter in config file

**Comment by bilalbioinfo** [comment]
working on it!!

**Comment by bilalbioinfo** [comment]
done - i run the preseq of big bam file (e.g., 58 Million mapped reads) and with step size (-s 1000000 that is set as default in the modules.config) it takes only 3 min and 1 cpu and 118Mb of memory. so we dont need to sub-sample!!
now user can turn off and on preseq in config file - 
8b270ac01c7c3d85dc42e0212b4f7f851f39d9db

have a look on dev-bilal branch
