### ISSUE TITLE
Split PROCESSED_FASTQ_RAW_BAM_QC subworkflow

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#39]
Separate QC for processed fastQ files and raw BAM files

**Comment by bilalbioinfo** [comment]
this is done. i also moved processed_fastq_qc above mapping. commit hash on dev-bilal: 409ba092ce89c35270f39238bfbbbc01d72a9f00

**Comment by verku** [comment]
Update documentation in `modules.config`

**Comment by bilalbioinfo** [comment]
Done - 3f275a4c3b712c5e83d3ebe3b44e643adea34739
rearranged some of the modules in the module.config to match the sub-workflows
