### ISSUE TITLE
Automatic selection of minimum read length from AMBER output

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#48]

**Comment by verku** [comment]
nf-core way of running an optional process:

in modules.config, add:
```
withName: 'MERGE_SDATA' {
        ext.when = params.merge_sdata
    }
```

alternatively: if-else clause in main workflow definition or subworkflow definition (more verbose)

**Comment by verku** [comment]
Sample-specific options:

- Add column to samplesheet

**Comment by bilalbioinfo** [comment]
This is done!
if params.read_len_cutoff is set to auto, the pipeline will estimate the reads len cutoff from amber results using bilal scripts, link to gihub provided. the threshold is 0.05 for double stranded lib and 0.01 for single stranded library, this info is take from the samples sheet.

**Comment by verku** [comment]
Read length parameters in config: use only one parameter that can be set to “auto” or an integer (e.g. 20)

**Comment by bilalbioinfo** [comment]
done  - 7b5d3e1721108dd0d170e1bd534c74ba8782a8d7 
and updated the config files templates !! d7676283078d42429b861b3d1b003477d0133a28
merging to dev-bilal
