### ISSUE TITLE
Mapping quality filter for the final bam

### ISSUE THREAD

**Issue by bilalbioinfo** [NBISweden/DNAharvester#58]
in the bam processing sub-workflow, mapping quality 25 should be applied for bams

**Comment by bilalbioinfo** [comment]
working on it

**Comment by verku** [comment]
Add module prior to first merging step

**Comment by verku** [comment]
Add parameter for MQ to config file

**Comment by verku** [comment]
Apply same MQ parameter in samtools depth module

**Comment by verku** [comment]
Since samtools depth is run on the final merged BAM files after MQ filtering, I removed the flag `-Q 30` entirely because there should not be any reads left with a MQ lower than the threshold specified in the configuration file.

**Comment by verku** [comment]
Check bugs in PR
Check when preseq is run - should be after MQ filtering
