### ISSUE TITLE
Pipeline output: CSV for database

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#7]
Get in touch with Bilal

**Comment by bilalbioinfo** [comment]
Hi @verku. The pipeline should output a CSV or tab-delimited file with the following columns, Thanks

Raw Reads
Merged Reads
Ref. Genome # name of the reference genome and version used in read_hervester
Mapping Program # in read_harvester this will probably be fixed to BWA aln
Mapped Reads
Filtered Reads
MQ Filter # should be set to 25 in read_harvester ?
Unique Reads
Coverage
Min Read Length
Max Read Length
Mean Read Length
Median Read Lenth:

**Comment by bilalbioinfo** [comment]
this is done! check branch dev-bilal. the output files is saved in the params.outdir/stats
