### ISSUE TITLE
memory and cpu are not being assigned to the job as asked for in the dardel profile!!

### ISSUE THREAD

**Issue by bilalbioinfo** [NBISweden/DNAharvester#73]
When  i run the pipeline with -profile dardel. it still limit the memeory to 6Gb due to this code exist in the main nextflow.config!!!! should be removed

// limit resources for test runs with small dataset
process {

    cpus   = 1
    memory = 6.GB
    time   = 1.h

    withLabel: process_single {
        cpus   = 1
        memory = 6.GB
        time   = 1.h
    }
    withLabel: process_low {
        cpus   = 2
        memory = 6.GB
        time   = 1.h
    }
    withLabel: process_medium {
        cpus   = 2
        memory = 6.GB
        time   = 1.h
    }
    withLabel: process_high {
        cpus   = 2
        memory = 6.GB
        time   = 2.h
    }
    withLabel: process_long {
        time   = 1.h
    }
    withLabel: process_high_memory {
        memory = 6.GB
    }
}

**Comment by verku** [comment]
TODO: Make sure there is a resource specification for test data
